version: '3'

services:
  mongodb:
     image: mongo:6.0.2
     ports:
       - '27017:27017'
     volumes:
       - mongo-data:/data/db
     networks:
       - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: backend
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/right-location
    ports:
      - '3000:3000'
    depends_on:
      - redis
    networks:
      - app-network

volumes: 
  mongo-data:

networks:
  app-network:
    driver: bridge
