version: '3'

services:
  mongodb:
     image: mongo:6.0.2
     ports:
       - '27017:27017'
     volumes:
       - mongo-data:/data/db
     networks:
       - app-network

  backend:
    build:
      context: .
      dockerfile: /apps/server/Dockerfile
    image: backend
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/right-location
    ports:
      - '3010:3010'
    depends_on:
      - mongodb
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    image: backend
    environment:
      - SERVER_URL=http://backend
    ports:
      - '3010:3010'
    depends_on:
      - mongodb
    networks:
      - app-network

  public:
    build:
      context: .
      dockerfile: /apps/public/Dockerfile
    image: backend
    environment:
      - SERVER_URL=http://backend
    ports:
      - '3010:3010'
    depends_on:
      - mongodb
    networks:
      - app-network

volumes: 
  mongo-data:

networks:
  app-network:
    driver: bridge
