version: '3'

services:
  redis:
    image: redis:7.0.5-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - app-network
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - ./services/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis:/data

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: backend
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - '3000:3000'
    depends_on:
      - redis
    networks:
      - app-network

volumes:
  redis-data: 

networks:
  app-network:
    driver: bridge
