export const TypeOfEdications = [
  "Voluntary Aided School",
  "Voluntary Controlled School",
  "LA Nursery School",
  "Community School",
  "Community Special School",
  "Free School",
  "Free School Special",
  "Free School - Alternative Provision",
  "Academy Special Sponsor Led",
  "Academy Converter",
  "Academy Alternative Provision Converter",
  "Academy Sponsor Led",
  "Academy Special Converter",
  "Academy Alternative Provision Sponsor Led",
  "University Technical College",
  "City Technology College",
  "Studio School",
  "Foundation School",
  "Foundation Special School",
  "Pupil Referral Unit",
  "Non-Maintained Special School",
];